CREATE SEQUENCE seq_usuario START 1 INCREMENT 1;
CREATE SEQUENCE seq_cargo START 1 INCREMENT 1;

-- INSERT CARGOS
INSERT INTO cargo (id_cargo, nome) VALUES (nextval('seq_cargo'), 'ROLE_ADMIN');
INSERT INTO cargo (id_cargo, nome) VALUES (nextval('seq_cargo'), 'ROLE_USUARIO');

-- INSERT USUÁRIOS
INSERT INTO usuario (id_usuario, login, email, senha) VALUES (nextval('seq_usuario'), 'admin','admin@gmail.com', '$2a$10$X.AxPaR2usWOKRyUT2ZX/.k5sdTQNkSUly3AlSibvxImFrNb9ulAu');
INSERT INTO usuario (id_usuario, login, email, senha) VALUES (nextval('seq_usuario'), 'user','user@gmail.com' ,'$2a$10$X.AxPaR2usWOKRyUT2ZX/.k5sdTQNkSUly3AlSibvxImFrNb9ulAu');


ALTER TABLE USUARIO
ADD COLUMN EMAIL VARCHAR(255);

ALTER TABLE USUARIO
ALTER COLUMN EMAIL SET NOT NULL;

ALTER TABLE USUARIO
ADD CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL);

select * from usuario u


CREATE sequence seq_jogos START 1 INCREMENT 1;

CREATE TABLE JOGOS (
    ID_JOGO INTEGER PRIMARY KEY DEFAULT nextval('seq_jogos'),
    TITULO VARCHAR(128) NOT NULL,
    ANO_LANCAMENTO SMALLINT NOT NULL,
    PRODUTORA VARCHAR(128) NOT NULL,
    AVG_RATING NUMERIC(4,2) CHECK (AVG_RATING >= 0 AND AVG_RATING <= 10),
    TOTAL_RATING INTEGER,
    IMG VARCHAR(528),
    GENERO VARCHAR(128)[],
    PLATAFORMAS VARCHAR(128)[],
    DESCRICAO TEXT
);

select * from JOGOS o

CREATE TABLE USUARIO_JOGO (
    ID_USUARIO INTEGER NOT NULL,
    ID_JOGO INTEGER NOT NULL,
    RATING NUMERIC(4,2) CHECK (RATING >= 0 AND RATING <= 10),
    FAVORITO BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY(ID_USUARIO),
    CONSTRAINT FK_USUARIO_JOGO_JOGO FOREIGN KEY (ID_JOGO) REFERENCES JOGOS(ID_JOGO),
    CONSTRAINT FK_USUARIO_JOGO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

INSERT INTO usuario_cargo VALUES (1, 1);